server:
  port: 8091
spring:
  application:
    name: test-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    host: 192.169.88.130
  data:
    mongodb:
      host: 192.169.88.130
      database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
ip:
  t:
    w: 12312123

leyou:
  jwt:
    pubKeyPath: E:\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
       /api/auth
       /api/search
       /api/user/register
       /api/user/check
       /api/user/code
       /api/item